### ISSUE TITLE
gradio_app error on startup

### ISSUE THREAD

**Issue by BahamutRU** [facebookresearch/vfusion3d#10]
```
Traceback (most recent call last):
  File "F:\NN\vfusion3d\gradio_app.py", line 251, in <module>
    model_output = LitModel3D(
  File "C:\Users\Bahamut\AppData\Roaming\Python\Python310\site-packages\gradio\component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
  File "C:\Users\Bahamut\AppData\Roaming\Python\Python310\site-packages\gradio_litmodel3d\litmodel3d.py", line 93, in __init__
    super().__init__(
  File "C:\Users\Bahamut\AppData\Roaming\Python\Python310\site-packages\gradio\component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: Component.__init__() got an unexpected keyword argument 'key'
```

Maybe, python version?
PyTorch 2.3 and CUDA 12.1 as needed.

**Comment by JunlinHan** [comment]
try updating them: 
gradio==4.31.4
gradio-litmodel3d==0.0.1

**Comment by BahamutRU** [comment]
> gradio==4.31.4 
Thx!
