### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'Resampling'

### ISSUE THREAD

**Issue by ehsanwwe** [facebookresearch/vfusion3d#7]
i got this error when i clone hugging face demo

python -m app
/home/ehsan/anaconda3/lib/python3.9/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)
model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.81G/1.81G [02:38<00:00, 11.2MB/s]
preprocessor_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 436/436 [00:00<00:00, 244kB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 548/548 [00:00<00:00, 901kB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 346M/346M [00:30<00:00, 11.5MB/s]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Downloading data from 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/isnet-general-use.onnx' to file '/home/ehsan/.u2net/isnet-general-use.onnx'.
100%|████████████████████████████████████████| 179M/179M [00:00<00:00, 957GB/s]
2024-08-13 08:18:57.147141232 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:456 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(onnxruntime::python::PySessionOptions&, const ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
Traceback (most recent call last):
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "/home/ehsan/PycharmProject/vfusion3d/VFusion3D/app.py", line 204, in step_1_generate_obj
    mesh_path, _ = generate_mesh(image, export_mesh=True)
  File "/home/ehsan/PycharmProject/vfusion3d/VFusion3D/app.py", line 157, in generate_mesh
    image = preprocess_image(image, source_size).to(model_wrapper.device)
  File "/home/ehsan/PycharmProject/vfusion3d/VFusion3D/app.py", line 37, in preprocess_image
    image = rembg_remove(image)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/rembg/bg.py", line 266, in remove
    masks = session.predict(img, *args, **kwargs)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/rembg/sessions/dis_general_use.py", line 27, in predict
    self.normalize(img, (0.485, 0.456, 0.406), (1.0, 1.0, 1.0), (1024, 1024)),
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/rembg/sessions/base.py", line 49, in normalize
    im = img.convert("RGB").resize(size, Image.Resampling.LANCZOS)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
2024-08-13 08:19:51.902660431 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:456 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(onnxruntime::python::PySessionOptions&, const ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
Traceback (most recent call last):
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/gradio/utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "/home/ehsan/PycharmProject/vfusion3d/VFusion3D/app.py", line 204, in step_1_generate_obj
    mesh_path, _ = generate_mesh(image, export_mesh=True)
  File "/home/ehsan/PycharmProject/vfusion3d/VFusion3D/app.py", line 157, in generate_mesh
    image = preprocess_image(image, source_size).to(model_wrapper.device)
  File "/home/ehsan/PycharmProject/vfusion3d/VFusion3D/app.py", line 37, in preprocess_image
    image = rembg_remove(image)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/rembg/bg.py", line 266, in remove
    masks = session.predict(img, *args, **kwargs)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/rembg/sessions/dis_general_use.py", line 27, in predict
    self.normalize(img, (0.485, 0.456, 0.406), (1.0, 1.0, 1.0), (1024, 1024)),
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/rembg/sessions/base.py", line 49, in normalize
    im = img.convert("RGB").resize(size, Image.Resampling.LANCZOS)
  File "/home/ehsan/anaconda3/lib/python3.9/site-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'

**Comment by JunlinHan** [comment]
wrong packages. did you set environments following our recommendations? you can try this to see if it can be fixed: https://stackoverflow.com/questions/71738218/module-pil-has-not-attribute-resampling

**Comment by ehsanwwe** [comment]
my problem solved by install CudaToolkit 12.4 >> cuNN >> TensorRT  From NVIDIA website to my WSL
